### ISSUE TITLE
MacOS catalina 10.15.1

### ISSUE THREAD

**Issue by aspel** [philroberts/pobfrontend#3]
Hello,
There is something wrong with resolution. 

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/1587659/70398198-9ee0d880-1a21-11ea-810e-26883f6e73d5.png">

**Comment by philroberts** [comment]
In the thread on PathOfBuilding, some people had interesting problems with retina displays, and IIRC someone posted a reasonably convincing-looking solution. I am unable to test, however.

**Comment by philroberts** [comment]
https://github.com/Openarl/PathOfBuilding/issues/28#issuecomment-320364512

The exchange in question. It looks a bit different to the problem you have but maybe there is something in common.

**Comment by deathbeam** [comment]
I noticed similar issue with `QT_AUTO_SCREEN_SCALE_FACTOR=1` on HiDPI displays on Linux. I think the issue is simply that pobfrontend is atm not DPI aware

**Comment by aspel** [comment]
This issue is related to macOS bandle format.

https://github.com/aspel/pobfrontend/blob/master/Info.plist#L27:L30

**Comment by deathbeam** [comment]
Alright then I will open the DPI issues with Linux as separate issue
